### ISSUE TITLE
Unable to find a workflow for class

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#1104]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | ?
| Operating System       | MacOS
| Zikula Target in Model | ZK15?
| Zikula Version         | 2.x-git
| PHP Version            | 5.6.x

### Expected behavior

no exception

### Actual behavior

This may be because of the differences in workflow between Core-1.5 and Core-2.0 (as I am running this ZK1.5 target on 2.0)

> Symfony\Component\Workflow\Exception\InvalidArgumentException:
Unable to find a workflow for class "Zikula\NewsModule\Entity\ArticleEntity".

>  at vendor/symfony/symfony/src/Symfony/Component/Workflow/Registry.php:61
  at Symfony\Component\Workflow\Registry->get(object(ArticleEntity))
     (modules/News/Helper/Base/AbstractWorkflowHelper.php:167)
  at Zikula\NewsModule\Helper\Base\AbstractWorkflowHelper->getActionsForObject(object(ArticleEntity))
     (modules/News/Form/Handler/Common/Base/AbstractEditHandler.php:452)
  at Zikula\NewsModule\Form\Handler\Common\Base\AbstractEditHandler->processForm(array('routeArea' => 'admin', 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array(100, 75), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper)))
     (modules/News/Form/Handler/Article/Base/AbstractEditHandler.php:48)
  at Zikula\NewsModule\Form\Handler\Article\Base\AbstractEditHandler->processForm(array('routeArea' => 'admin', 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array(100, 75), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper)))
     (modules/News/Controller/Base/AbstractArticleController.php:312)
  at Zikula\NewsModule\Controller\Base\AbstractArticleController->editInternal(object(Request), true)
     (modules/News/Controller/Base/AbstractArticleController.php:272)
  at Zikula\NewsModule\Controller\Base\AbstractArticleController->adminEditAction(object(Request))
     (modules/News/Controller/ArticleController.php:133)
  at Zikula\NewsModule\Controller\ArticleController->adminEditAction(object(Request))
  at call_user_func_array(array(object(ArticleController), 'adminEditAction'), array(object(Request)))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (index.php:18)

### Steps to reproduce
`/news/admin/article/edit` (attempting to crate a new article)

**Comment by Guite** [comment]
> because of the differences in workflow between Core-1.5 and Core-2.0

Yes.
In 2.0 you need to replace `workflow:` by `framework:` here:
https://github.com/zikula-modules/News/blob/5.0-prototype/Resources/workflows/none.yml#L1
https://github.com/zikula-modules/News/blob/5.0-prototype/Resources/workflows/standard.yml#L1

See also:
https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/controller/workflows/Definition.xtend#L72

**Comment by Guite** [comment]
just a thought: maybe we should let the new News target 2.0 instead of 1.5 directly (since the old module still works in 1.5)...

**Comment by craigh** [comment]
> maybe we should let the new News target 2.0 instead of 1.5

yes. we need a 2.0 compatible module.

**Comment by Guite** [comment]
Done in https://github.com/zikula-modules/News/pull/167

**Comment by craigh** [comment]
I still get this error with the updated version:

> Symfony\Component\Workflow\Exception\InvalidArgumentException:
Unable to find a workflow for class "Zikula\NewsModule\Entity\ArticleEntity".

>  at vendor/symfony/symfony/src/Symfony/Component/Workflow/Registry.php:61
  at Symfony\Component\Workflow\Registry->get(object(ArticleEntity))
     (modules/News/Helper/Base/AbstractWorkflowHelper.php:167)
  at Zikula\NewsModule\Helper\Base\AbstractWorkflowHelper->getActionsForObject(object(ArticleEntity))
     (modules/News/Form/Handler/Common/Base/AbstractEditHandler.php:452)
  at Zikula\NewsModule\Form\Handler\Common\Base\AbstractEditHandler->processForm(array('routeArea' => 'admin', 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array(100, 75), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper)))
     (modules/News/Form/Handler/Article/Base/AbstractEditHandler.php:48)
  at Zikula\NewsModule\Form\Handler\Article\Base\AbstractEditHandler->processForm(array('routeArea' => 'admin', 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array(100, 75), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper)))
     (modules/News/Controller/Base/AbstractArticleController.php:312)
  at Zikula\NewsModule\Controller\Base\AbstractArticleController->editInternal(object(Request), true)
     (modules/News/Controller/Base/AbstractArticleController.php:272)
  at Zikula\NewsModule\Controller\Base\AbstractArticleController->adminEditAction(object(Request))
     (modules/News/Controller/ArticleController.php:133)
  at Zikula\NewsModule\Controller\ArticleController->adminEditAction(object(Request))
  at call_user_func_array(array(object(ArticleController), 'adminEditAction'), array(object(Request)))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (index.php:18)

**Comment by Guite** [comment]
Try moving the module from `modules/News/` to `modules/Zikula/NewsModule`...

**Comment by craigh** [comment]
please reopen until I have time to look into it

**Comment by Guite** [comment]
This is definitely caused by `modules/<moduleName>` instead of `modules/<vendor>/<moduleName>`. See https://github.com/zikula/core/blob/2.0/src/lib/Zikula/Bundle/WorkflowBundle/DependencyInjection/ZikulaWorkflowExtension.php#L48

**Comment by craigh** [comment]
Then this is improper. A module cannot assume path information like that. You should use `$bundle->getPath() . '/Resources/workflows'`

**Comment by Guite** [comment]
See https://github.com/zikula/core/issues/3767
