### ISSUE TITLE
Compile Error: Cannot use Botanyorg\ConferenceModule\Helper\WorkflowHelper as WorkflowHelper because the name is already in use

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#764]
FatalErrorException in NotificationHelper.php line 32: Compile Error: Cannot use Botanyorg\ConferenceModule\Helper\WorkflowHelper as WorkflowHelper because the name is already in use

    in NotificationHelper.php line 32
    at DebugClassLoader->loadClass() in DebugClassLoader.php line 21
    at spl_autoload_call() in DebugClassLoader.php line 21
    in DebugClassLoader.php line 169
    at DebugClassLoader->loadClass() in ServiceDefinitionValidator.php line 64
    at spl_autoload_call() in ServiceDefinitionValidator.php line 64
    at class_exists() in ServiceDefinitionValidator.php line 64
    at ServiceDefinitionValidator->validateClass() in ServiceDefinitionValidator.php line 41
    at ServiceDefinitionValidator->validateAttributes() in ServiceDefinitionValidator.php line 32
    at ServiceDefinitionValidator->validate() in BatchServiceDefinitionValidator.php line 28
    at BatchServiceDefinitionValidator->validate() in ValidateServiceDefinitionsPass.php line 35
    at ValidateServiceDefinitionsPass->process() in Compiler.php line 104
    at Compiler->compile() in ContainerBuilder.php line 597
    at ContainerBuilder->compile() in ContainerBuilder.php line 110
    at ContainerBuilder->compile() in Kernel.php line 519
    at Kernel->initializeContainer() in ZikulaKernel.php line 325
    at ZikulaKernel->initializeContainer() in Kernel.php line 133
    at Kernel->boot() in ZikulaKernel.php line 104
    at ZikulaKernel->boot() in bootstrap.php line 62
    in index.php line 14
    at {main}() in index.php line 0

**Comment by Guite** [comment]
Fixed in 821846c2e2f2b8cf0c0872352e050aedf9ed3c37

**Comment by robbrandt** [comment]
@Guite I am still getting this error. No change from last time.  The missing semicolons from the  EditHandler.php bug are still there too.  I must be doing something wrong to test this.

I went to webgen and generate new, using the _**same**_ .mostapp I used previously.  No new upload.
I downloaded and uncompressed the new Conference.mostapp.zip
I deleted the previous module files from my test site
I copied the new module files into the ConferenceModule directory.

What am I missing?  I fixed the missing semicolons manually since I knew what the problem was there.  Stuck on this one though.

**Comment by robbrandt** [comment]
I found how to manually edit out this bug in your commit 
https://github.com/Guite/MostGenerator/commit/821846c2e2f2b8cf0c0872352e050aedf9ed3c37

**Comment by Guite** [comment]
In webgen the square at the top right is currently red (not green). If you click on it's text it shows you which git revision the webgen is currently using. As I am changing the build infrastructure generator deployment is not working again yet. This is why latest updates are not included in the webgen yet.

**Comment by Guite** [comment]
@robbrandt webgen is up again :smile:
